spring:
  application:
    name: boot-jsp

  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# 포트
server:
  port: 8090

# JSP를 재실행 없이 반영
#  servlet:
#    jsp:
#      init-parameters:
#        development: true








